# Generated by Django 5.2.8 on 2026-06-24 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('CPU', 'პროცესორი (CPU)'), ('GPU', 'ვიდეობარათი (GPU)'), ('RAM', 'ოპერატიული (RAM)'), ('MOBO', 'დედაპლატა (Motherboard)'), ('SSD', 'მეხსიერება (SSD)'), ('PSU', 'კვების ბლოკი (PSU)')], max_length=10)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wattage', models.IntegerField(help_text='ენერგომოხმარება ვატებში')),
            ],
        ),
        migrations.CreateModel(
            name='PCBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('components', models.ManyToManyField(related_name='builds', to='configurator.component')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
